# Generated by Django 3.0.8 on 2020-08-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meiajuda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='tipo',
            new_name='categoria',
        ),
    ]
