# Generated by Django 3.0.8 on 2020-08-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15)),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.TextField(max_length=240)),
                ('cidade', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('imagem', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(blank=True, max_length=15, null=True)),
                ('symbol', models.CharField(blank=True, max_length=3, null=True)),
                ('atomicNumber', models.IntegerField(blank=True, default=0)),
                ('atomicMass', models.FloatField(blank=True, default=0)),
                ('neutrons', models.IntegerField(blank=True, default=0)),
                ('protons', models.IntegerField(blank=True, default=0)),
                ('electrons', models.IntegerField(blank=True, default=0)),
                ('phase', models.CharField(blank=True, max_length=35, null=True)),
                ('radioactive', models.CharField(blank=True, max_length=10, null=True)),
                ('tp', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
    ]
