# Generated by Django 3.0.8 on 2020-07-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='atomicMass',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='atomicNumber',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='electrons',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='element',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='element',
            name='neutrons',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='phase',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='element',
            name='protons',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='radioactive',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='element',
            name='symbol',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='element',
            name='type',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
