# Generated by Django 3.0.8 on 2020-07-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20200720_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='radioactive',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
