# Generated by Django 3.0.8 on 2020-07-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_auto_20200723_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='atomicMass',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='atomicNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='electrons',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='neutrons',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='protons',
            field=models.IntegerField(null=True),
        ),
    ]
